### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLFlowClient.jl#39]

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:

(fix)
- Solving Documenter pipeline failing on building
- Increasing project maintainability
- Increasing code test coverage

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:

### Addings
- URI default to `ENV["MLFLOW_TRACKING_URI"]` if exists, just as `mlflow` documentation mentions.

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:

- New project structure to ensure better maintainability.
- Adopting Blue Style to improve readability.
- Pair with all the types from MLflow REST API.
- Implement all the endpoints from MLflow latest release.
- Improved documentation with multiple dispatch definitions.
- Simplify function definitions.
- Simplify test definitions.

> [!IMPORTANT]
> This update comes with some breaking changes. Projects like [MLJFlow.jl](https://github.com/JuliaAI/MLJFlow.jl) will need to update carefully. It will be the same with personal projects.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=main

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:
### New features
- MLFlow 3.0 API Endpoints
    - Scorers API
    - Gateway API (Databricks-specific)
        - Secrets management
        - Model definitions
        - Endpoints
        - Endpoint bindings
        - Budgets
    - Prompt optimization API
    - **MLFlow Artifacts API**

### Modifications (breaking changes)
- `logmetric`
    - Added parameters: `model_id`, `dataset_name, `dataset_digest`

### Notes
- Gateway API
    - Gateway endpoints are Databricks-specific features
    - Tests will automatically skip if not using a Databricks tracking URI
    - Warning message displayed when attempting to run gateway tests on non-Databricks servers
- Prompt optimization API
    - Requires evaluation datasets to be present on the server
    - Tests gracefully skip with warnings if required resources are not available
- MLFlow Artifacts API
    - Uses `mlflow-artifacts` prefix (separate from main MLFlow API)
    - Multipart upload support for large files

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:

### New features
- Gateway services now work on any MLflow 3.x server (removed Databricks-only restriction)
- `updategatewaymodeldefinition` and `updategatewayendpoint` now expose all REST API parameters
- `WebhookEntity.BUDGET_POLICY` enum value added
- Dict constructors for `FileInfo` and `MultipartUploadCredential`
- Webhook docs page added; missing entries added to existing doc pages

### Bug fixes
- `updaterun`: `run_name` now defaults to `missing`; fixed `Integer(missing)` crash when `status` omitted
- `detachmodelfromgatewayendpoint`: changed from DELETE to POST
- `testwebhook`: fixed response key (`"result"` not `"test_result"`)
- `listwebhooks`: empty `page_token` no longer sent (caused server `INTERNAL_ERROR`)
- `searchexperiments`, `searchruns`, `searchregisteredmodels`, `searchmodelversions`: same empty-string fix
- `createexperiment`: workaround for MLflow 3.x basic-auth permission race condition
- `GatewayEndpoint`: Added `experiment_id` and `usage_tracking` fields
- Removed dead `mlfpatch_v3` function

### Breaking changes
- `WebhookStatus.INACTIVE` renamed to `DISABLED`
- `WebhookEntity.PROMPT_VERSION_ALIAS` renamed to `PROMPT_ALIAS`
- `attachmodeltogatewayendpoint` returns `GatewayEndpointModelMapping` instead of `GatewayEndpoint`
- Gateway type fields renamed (`creation_timestamp` to `created_at`, and `update_timestamp` to `last_updated_at`)
- `GatewayEndpoint.model_configs` renamed to `model_mappings`
- Search functions: `filter`/`page_token` type changed from `String` to `Union{String,Missing}`
- `updategatewayendpoint`: `config` param replaced with explicit API fields


> [!NOTE]
> Previous version (`v0.8.0`) was tested against a `mlflow==3.10` installation. An error occurred while updating, so apologies for the inconvenience.

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=main

Release notes:

### New features
- Full MLflow 3.14 REST API coverage
    - Workspaces
    - RBAC: roles and per-user permissions
    - Label schemas
- Managed MLflow test server via CondaPkg (tests no longer require an external server), with parallel CI across Julia versions

### Bug fixes
- HTTP.jl 2.x: send `Connection: close` to avoid `unexpected EOF while reading HTTP/1 data` from stale keep-alive connections against MLflow's server
- Error handling now rethrows connection/parse errors (e.g. `HTTP.ParseError`) instead of masking them with a `FieldError` on `e.response`
- Replaced deprecated `readtimeout` with `read_idle_timeout` in the test-server health check
- Webhook tests: pin `MLFLOW_WEBHOOK_SECRET_ENCRYPTION_KEY` so multi-worker MLflow 3.14 servers can decrypt webhook secrets (fixes an intermittent 500 on webhook delete)

### Breaking changes
- Requires HTTP.jl 2
- Per-resource permission API removed in favor of RBAC: the `ExperimentPermission`/`RegisteredModelPermission` types and the `create/get/update/deleteexperimentpermission` and `create/get/update/deleteregisteredmodelpermission` functions are gone
- `Experiment` gained a `workspace` field, so its positional constructor now takes 9 arguments
